/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   signals.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: aurlic <aurlic@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/02/14 10:57:41 by aurlic            #+#    #+#             */
/*   Updated: 2024/02/14 16:25:07 by aurlic           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/minishell.h"

static void handler(int sig)
{
	if (sig == SIG_INT)
	{

	}
}

void	handle_signals(int action)
{
	struct sigaction	sig;

	signal(SIGTSTP, SIG_IGN);
	if (action == 1)
	{
		// IN CASE OF HEREDOC -> HANDLE CTRL D IN HERE DOC
	}
	
	sig.sa_flags = SA_RESTART;
	sig.sa_handler = &ft_sig_handling;
	sigaction(SIGINT, &sa_sig, NULL);
	signal(SIGQUIT, SIG_IGN);
}


Purpose: This function handles the SIGINT signal, which is typically generated by 
pressing Ctrl+C on the keyboard.
Usage:
Upon receiving the SIGINT signal, it prints a newline character (\n) to move 
to a new line.
It calls rl_on_new_line() and rl_replace_line("", 0) functions from the Readline 
library to clear the current input line.
It updates the global variable g_ret_val to 130, indicating that the process 
was terminated by an interrupt signal.